source/connection-strings/connection-strings.txt, source/connection-strings/mongodb-database-connection-strings.txt, source/connection-strings/relational-database-connection-strings.txt, source/includes/uri-usage-disclaimer.rst
Connection String drawer conversion from markdown to snooty.
https://docs-mongodbcom-staging.corp.mongodb.com/docs-relational-migrator/docsworker-xlarge/DOCSP-30626/connection-strings/connection-strings/
https://docs-mongodbcom-staging.corp.mongodb.com/docs-relational-migrator/docsworker-xlarge/DOCSP-30626/connection-strings/mongodb-database-connection-strings/
https://docs-mongodbcom-staging.corp.mongodb.com/docs-relational-migrator/docsworker-xlarge/DOCSP-30626/connection-strings/relational-database-connection-strings/
https://jira.mongodb.org/browse/DOCSP-30626
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6487661267a273b8169d86b1
=> DOCSP-30626 Connection String Drawer

source/diagrams/diagrams.txt, source/diagrams/navigate-diagrams/navigate-diagrams.txt, source/diagrams/understand-diagrams.txt, source/mapping-rules/edit-rules.txt, source/mapping-rules/mapping-rule-options/embedded-array.txt
Add new pages for Migrate Diagrams
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6489f0ee67a273b816340d88
- [Diagrams](https://docs-mongodbcom-staging.corp.mongodb.com/docs-relational-migrator/docsworker-xlarge/DOCSP-30631/diagrams/diagrams/)
- [Understand Diagrams](https://docs-mongodbcom-staging.corp.mongodb.com/docs-relational-migrator/docsworker-xlarge/DOCSP-30631/diagrams/understand-diagrams/)
https://jira.mongodb.org/browse/DOCSP-30631
=> (DOCSP-30631): Migrate Diagrams section to snooty

source/index.txt, source/migration-scenarios.txt
Add new page for migration scenarios. The material for this page comes from this [Google Doc](https://docs.google.com/document/d/1iacL04fhEQWoh6EqMaLAF7qxvUqpXQZ8oP5o_IqPBZI/edit), which Tom approved.
Note, I notice that we also have an Introduction page below the landing page. I'm not sure what's going to go on that page, but let me know if this content belongs there instead.
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=648b3b5767a273b816830fad
https://docs-mongodbcom-staging.corp.mongodb.com/docs-relational-migrator/docsworker-xlarge/DOCSP-30752/migration-scenarios/
https://jira.mongodb.org/browse/DOCSP-30752
=> (DOCSP-30752): Migration patterns page

source/index.txt, source/projects/configure-settings.txt, source/release-notes.txt
Changelogs added to Relational Migrator index page.
Also removed a duplicate ref causing a build error.
https://docs-mongodbcom-staging.corp.mongodb.com/docs-relational-migrator/docsworker-xlarge/DOCSP-30867/release-notes/
https://jira.mongodb.org/browse/DOCSP-30867
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64925a93259a8493e541bdbe
=> DOCSP-30867 Add 1.0 Changelogs

source/includes/project-initial-mappings-att.rst, source/includes/project-initial-mappings.rst, source/index.txt, source/projects/create-project-live-connection.txt, source/projects/create-project-loading-schema-files.txt, source/projects/create-project-sample-schema.txt
Add details to each project creation page about the recomended schema options for inital mappings.
This happens in the About this Task section and the task step numbers.
Also includes a few clean ups in the text.
https://docs-mongodbcom-staging.corp.mongodb.com/docs-relational-migrator/docsworker-xlarge/DOCSP-30123/projects/create-project-live-connection/#about-this-task
(Step 7) 
https://docs-mongodbcom-staging.corp.mongodb.com/docs-relational-migrator/docsworker-xlarge/DOCSP-30123/projects/create-project-live-connection/
https://jira.mongodb.org/browse/DOCSP-30123
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6491f7c1259a8493e529881c
=> DOCSP-30123 Project with a Recommended Schema Details

source/code-generation/code-generation.txt, source/connection-strings/connection-strings.txt, source/connection-strings/mongodb-database-connection-strings.txt, source/connection-strings/relational-database-connection-strings.txt, source/diagrams/diagrams.txt, source/diagrams/navigate-diagrams/navigate-diagrams.txt, source/diagrams/navigate-diagrams/working-with-entities/working-with-entities.txt, source/jobs/data-verification/data-verification.txt, source/jobs/sync-jobs.txt, source/mapping-rules/mapping-rule-options/mapping-rule-options.txt, source/table-filters/apply-table-filters.txt, source/table-filters/table-filters.txt
- Adding `on this page` directive to pages which didnt have. 
- Adding `Get Started` h1 to reference pages which previously did not have.
- Added refs to table filters and apply table filters pages.
Added on this page:
- [/code-generation/code-generation/](https://docs-mongodbcom-staging.corp.mongodb.com/docs-relational-migrator/docsworker-xlarge/DOCSP-30781/code-generation/code-generation/)
- [/connection-strings/connection-strings/](https://docs-mongodbcom-staging.corp.mongodb.com/docs-relational-migrator/docsworker-xlarge/DOCSP-30781/connection-strings/connection-strings/)
- [/connection-strings/mongodb-database-connection-strings/](https://docs-mongodbcom-staging.corp.mongodb.com/docs-relational-migrator/docsworker-xlarge/DOCSP-30781/connection-strings/mongodb-database-connection-strin …
=> DOCSP-30781 Add On This Page

source/jobs/data-verification/data-verification.txt, source/projects/projects.txt
CTRL + F for "relation " and replace with "relational " where appropriate.
https://docs-mongodbcom-staging.corp.mongodb.com/docs-relational-migrator/docsworker-xlarge/DOCSP-30917/projects/projects/
https://docs-mongodbcom-staging.corp.mongodb.com/docs-relational-migrator/docsworker-xlarge/DOCSP-30917/jobs/data-verification/data-verification/
https://jira.mongodb.org/browse/DOCSP-30917
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=649452c7423952aeb95c67d9
=> DOCSP-30917 Relation Typo

source/includes/mapping-options-preview.rst, source/index.txt, source/mapping-rules/mapping-rules.txt, source/mapping-rules/new-rules-suggested-mappings.txt
Adding visual to mapping rules stub page for the blue box preview functionality. Also adding a little detail to the note directive for suggested mapping rules.
https://docs-mongodbcom-staging.corp.mongodb.com/docs-relational-migrator/docsworker-xlarge/DOCSP-30203/mapping-rules/mapping-rules/#preview-mapping-rules
https://docs-mongodbcom-staging.corp.mongodb.com/docs-relational-migrator/docsworker-xlarge/DOCSP-30203/mapping-rules/new-rules-suggested-mappings/#steps
https://jira.mongodb.org/browse/DOCSP-30203
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64aec475423952aeb98e7d78
=> DOCSP-30203 Suggested Mapping Rules Are Previewed

snooty.toml, source/index.txt, source/migration-scenarios.txt, source/supported-databases.txt
Source database ref page.
STAGING: https://docs-mongodbcom-staging.corp.mongodb.com/docs-relational-migrator/docsworker-xlarge/DOCSP-31387/supported-databases/ 
JIRA: https://jira.mongodb.org/browse/DOCSP-31387
BUILD: https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64bac0d687b3b36046cbb9a3
=> DOCSP-31387 source database ref page

source/index.txt, source/release-notes.txt
1.1.3 Relational Migrator release notes. Also attempting to fix the external link icon on the download button by adding www to the download link on the landing page (this will only be visible in production).
https://docs-mongodbcom-staging.corp.mongodb.com/docs-relational-migrator/docsworker-xlarge/DOCSP-31632/release-notes/
https://jira.mongodb.org/browse/DOCSP-31632
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64c15ea987b3b3604642e668
=> DOCSP-31632 1.1.3 Release Notes

source/diagrams/diagrams.txt, source/table-filters/apply-table-filters.txt
Adding mention of the filter icon which is shown when you add Table filters to tables in Relational Migrator.
https://docs-mongodbcom-staging.corp.mongodb.com/docs-relational-migrator/docsworker-xlarge/DOCSP-27625/table-filters/apply-table-filters/
https://jira.mongodb.org/browse/DOCSP-27625
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64c916cb87b3b36046e84fde
=> DOCSP-27625 Add Table Filter Icon Mention to Table Filters

source/supported-databases.txt
Adding explicit content highlighting supported MongoDB versions.
https://docs-mongodbcom-staging.corp.mongodb.com/docs-relational-migrator/docsworker-xlarge/DOCSP-31855/supported-databases/#mongodb-database-and-versions
https://jira.mongodb.org/browse/DOCSP-31855
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64cd03f367dbe91010e34875
=> DOCSP-31855 Add MongoDB Versions to Support Page

source/installation.txt
Changes mention of "Early Access" to "Private Preview"
https://docs-mongodbcom-staging.corp.mongodb.com/docs-relational-migrator/docsworker-xlarge/DOCSP-32401-change-language-private-preview/installation/#:~:text=team%20to%20discuss-,private%20preview,-opportunities.
https://jira.mongodb.org/browse/DOCSP-32401
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64ecb44324fcc731b422d508
=> DOCSP-32401 Change 'Early Access' to 'Private Preview'

source/release-notes.txt
Relational Migrator 1.2.0 release notes
STAGING: https://docs-mongodbcom-staging.corp.mongodb.com/docs-relational-migrator/docsworker-xlarge/DOCSP-32840/release-notes/#1.2.0-changelog
JIRA: https://jira.mongodb.org/browse/DOCSP-32840
BUILD: https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64f7613424fcc731b47d2ba3
=> DOCSP-32840 1.2.0 release notes

source/facets.toml
Hey @sarah-olson-mongodb!
Here's the facet.toml file for the relational migrator repo.  Please merge if it looks good to you!
Thank you!
Sarah
=> DOCSP-32483 programmatic tagging script for relational migrator repo

source/jobs/stopping-jobs.txt
Add stop / resume considerations to stop job page.
https://docs-mongodbcom-staging.corp.mongodb.com/docs-relational-migrator/docsworker-xlarge/DOCSP-33185/jobs/stopping-jobs/
https://jira.mongodb.org/browse/DOCSP-33185
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=650deb0e492df295cff09272
=> DOCSP-33185 Stop / Resume Sync Job Considerations

source/release-notes.txt
1.3 Release notes.
https://docs-mongodbcom-staging.corp.mongodb.com/docs-relational-migrator/docsworker-xlarge/DOCSP-33334/release-notes/#1.3.0-changelog
https://jira.mongodb.org/browse/DOCSP-33334
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6514912a492df295cf6ec804
=> DOCSP-33334 Relational Migrator 1.3 Release Notes

source/release-notes.txt
Relational Migrator 1.3.1 Release Notes.
https://preview-mongodbianfmongodb.gatsbyjs.io/docs-relational-migrator/DOCSP-33566/release-notes/#1.3.1-changelog
https://jira.mongodb.org/browse/DOCSP-33566
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65254c4b885de6b26b25927d
=> DOCSP-33566 1.3.1 Changelog

config/redirects
Adding `docs/` to the prefix variable in `config/redirects`. 
Mut Output:
```
(base) ➜  docs-relational-migrator git:(DOCSP-33593) mut-redirects config/redirects                               
Redirect 301 /docs/relational-migrator/mapping-rules/calculated-fields/calculated-fields https://www.mongodb.com/docs/relational-migrator/mapping-rules/fields/calculated-fields/calculated-fields/
Redirect 301 /docs/relational-migrator/mapping-rules/calculated-fields/calculated-fields/add-calculated-fields https://www.mongodb.com/docs/relational-migrator/mapping-rules/fields/calculated-fields/calculated-fields/add-calculated-fields
Redirect 301 /docs/relational-migrator/mapping-rules/calculated-fields/calculated-fields/view-calculated-fields …
```
=> DOCSP-33593 Fix Relational Migrator Redirects

source/release-notes.txt
1.3.2 Release notes.
https://preview-mongodbianfmongodb.gatsbyjs.io/docs-relational-migrator/DOCSP-33867/release-notes/#1.3.2-changelog
https://jira.mongodb.org/browse/DOCSP-33867
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=653bf41a3ede3ec111b50c7f
=> DOCSP-33867 1.3.2 Release Notes

snooty.toml, source/release-notes.txt
1.3.3 Release Notes.
https://preview-mongodbianfmongodb.gatsbyjs.io/docs-relational-migrator/DOCSP-34112/release-notes/#1.3.3-changelog
https://jira.mongodb.org/browse/DOCSP-34112
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=654a3b335b686d6bd9ff3d36
=> DOCSP-34112 1.3.3 Release Notes

source/code-generation/query-converter/convert-views.txt
Task page, how to convert SQL views to MongoDB code.
https://preview-mongodbianfmongodb.gatsbyjs.io/docs-relational-migrator/DOCSP-33246/code-generation/query-converter/convert-views/
https://jira.mongodb.org/browse/DOCSP-33246
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=654e990e5b686d6bd9347a41
=> DOCSP-33246 Convert Views Content

source/code-generation/query-converter.txt, source/code-generation/query-converter/refresh-database-objects.txt
Task page, how to refresh database objects in the query converter.
https://preview-mongodbianfmongodb.gatsbyjs.io/docs-relational-migrator/DOCSP-33003/code-generation/query-converter/refresh-database-objects/
https://jira.mongodb.org/browse/DOCSP-33003
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=655284ae5b686d6bd9f6f2c0
=> DOCSP-33003 Refresh Database Objects

source/table-filters/apply-table-filters.txt, source/table-filters/delete-table-filters.txt, source/table-filters/edit-table-filters.txt, source/table-filters/table-filters.txt
Adding delete and edit table filter tasks to the table filter drawer. Also updating the apply table filter page to use the `procedure` directive.
https://preview-mongodbianfmongodb.gatsbyjs.io/docs-relational-migrator/DOCSP-27646/table-filters/edit-table-filters/
https://preview-mongodbianfmongodb.gatsbyjs.io/docs-relational-migrator/DOCSP-27646/table-filters/delete-table-filters/
https://jira.mongodb.org/browse/DOCSP-27646
https://jira.mongodb.org/browse/DOCSP-27647
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=656741ad7a5cb5fef529ded8
=> DOCSP-27647 Add Delete and Edit Table Filter Content

source/diagrams/diagrams.txt, source/includes/fact-hackolade-integration.rst, source/release-notes.txt
1.4.3 Release Notes. Also adding a small call out to the Hackolade integration suggested in 
[DOCSP-34431](https://jira.mongodb.org/browse/DOCSP-34431) to the diagram page. 
https://preview-mongodbianfmongodb.gatsbyjs.io/docs-relational-migrator/DOCSP-34885/diagrams/diagrams/
https://preview-mongodbianfmongodb.gatsbyjs.io/docs-relational-migrator/DOCSP-34885/release-notes/#1.3.4-changelog
https://jira.mongodb.org/browse/DOCSP-34885
https://jira.mongodb.org/browse/DOCSP-34431
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=657741a97a5cb5fef502b8ac
=> DOCSP-34885 1.4.3 Release Notes

source/index.txt, source/supported-databases.txt
Adding Sybase ASE to supported database page and the index page of the docs.
https://preview-mongodbianfmongodb.gatsbyjs.io/docs-relational-migrator/DOCSP-34984/ (Data Synchronization Tab).
https://preview-mongodbianfmongodb.gatsbyjs.io/docs-relational-migrator/DOCSP-34984/supported-databases/
https://jira.mongodb.org/browse/DOCSP-34984
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=657b59ba7a5cb5fef5360979
=> DOCSP-34984 Add Sybase ASE to supported database

snooty.toml, source/index.txt, source/prerequisites.txt, source/prerequisites/my-sql.txt, source/prerequisites/oracle.txt, source/prerequisites/postgres.txt, source/prerequisites/sql-server.txt
Staging the TOC for the Data Migration Prerequisites content.  
https://preview-mongodbianfmongodb.gatsbyjs.io/docs-relational-migrator/DOCSP-34685/prerequisites/
https://jira.mongodb.org/browse/DOCSP-34685
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6568bfdf7a5cb5fef593e331
=> DOCSP-34685 Stage TOC For Prereq Content

source/supported-databases.txt
Update RM supported databases topic to cover SQL Server 2012
https://preview-mongodbltranmdb2.gatsbyjs.io/docs-relational-migrator/DOCSP-34588/supported-databases/
https://jira.mongodb.org/browse/DOCSP-34588
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=657b6bf57a5cb5fef53ca185
=> DOCSP 34588 Update RM supported databases topic to cover SQL Server 2012

source/supported-databases.txt
moving Sybase limitation to supported versions row (based on feedback in https://github.com/mongodb/docs-relational-migrator/pull/75 )
https://preview-mongodbltranmdb2.gatsbyjs.io/docs-relational-migrator/DOCSP-35183/supported-databases/
https://jira.mongodb.org/browse/DOCSP-35183
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6584572077a86a479bbc6a38
=> DOCSP-35183 editing Sybase row

source/diagrams/manage-diagrams/create-diagrams.txt
Making title singular and editing for minimalism
https://preview-mongodbltranmdb2.gatsbyjs.io/docs-relational-migrator/DOCSP-35617/diagrams/manage-diagrams/create-diagrams/#create-a-diagram
https://jira.mongodb.org/browse/DOCSP-35617
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65a16b35dcc0144a51b02064
=> DOCSP-35617 updating Create a Diagram title and minimalism edits

source/release-notes.txt
Fixing the H1 `1.3.4` -> `1.4.3`. 
https://preview-mongodbianfmongodb.gatsbyjs.io/docs-relational-migrator/DOCSP-35643/release-notes/
https://jira.mongodb.org/browse/DOCSP-35643
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65a684fddcc0144a51db13d2
=> DOCSP-35643 Correct Latest Release Version

source/release-notes.txt
1.4.4 release notes
https://preview-mongodbltranmdb2.gatsbyjs.io/docs-relational-migrator/DOCSP-35990/release-notes/#1.4.4-changelog
https://jira.mongodb.org/browse/DOCSP-35990
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65b7efd994771f7657d0908c
=> DOCSP-35990 1.4.4 release notes

source/installation/install-on-a-single-machine/install-mac.txt, source/installation/install-on-a-single-machine/install-rhel.txt, source/installation/install-on-a-single-machine/install-ubuntu.txt, source/installation/install-on-a-single-machine/install-windows.txt, source/installation/install-on-an-unattended-server/debian-server-installation/install-debian-server.txt, source/installation/install-on-an-unattended-server/rhel-centos-server-installation/install-rhel-server.txt, source/installation/install-on-an-unattended-server/windows-server-installation/install-windows-server.txt
updating RM installer links
https://preview-mongodbltranmdb2.gatsbyjs.io/docs-relational-migrator/DOCSP-30032/installation/install-on-a-single-machine/install-windows/
https://preview-mongodbltranmdb2.gatsbyjs.io/docs-relational-migrator/DOCSP-30032/installation/install-on-a-single-machine/install-mac/
https://preview-mongodbltranmdb2.gatsbyjs.io/docs-relational-migrator/DOCSP-30032/installation/install-on-a-single-machine/install-ubuntu/
https://preview-mongodbltranmdb2.gatsbyjs.io/docs-relational-migrator/DOCSP-30032/installation/install-on-a-single-machine/install-ubuntu/
https://preview-mongodbltranmdb2.gatsbyjs.io/docs-relational-migrator/DOCSP-30032/installation/install-on-an-unattended-server/windows-server-installation/install-windows-server/ …
=> DOCSP-30032 updating RM installer links

source/release-notes.txt
RM 1.4.6 Release Notes.
https://preview-mongodbianfmongodb.gatsbyjs.io/docs-relational-migrator/DOCSP-36712/release-notes/
https://jira.mongodb.org/browse/DOCSP-36712
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65cbe077cbcd269fa5e4264c
=> DOCSP-36712 1.4.6 Release Notes

source/includes/fact-data-prep-oracle-step1.rst, source/includes/fact-short-sync-job-desc.rst, source/prerequisites/oracle.txt, source/prerequisites/sql-server.txt
Task page for using Oracle with Relational Migrator / Data pre-reqs.
https://preview-mongodbianfmongodb.gatsbyjs.io/docs-relational-migrator/DOCSP-34264/prerequisites/oracle/
https://jira.mongodb.org/browse/DOCSP-34264/
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65df6f9571111659822cb58f
=> DOCSP-34264 Add Oracle Prereq Content

source/release-notes.txt
RM 1.5.0 Release Notes.
https://preview-mongodbianfmongodb.gatsbyjs.io/docs-relational-migrator/DOCSP-37370/release-notes/#1.5.0-changelog
https://jira.mongodb.org/browse/DOCSP-37370
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65e720e311db7b0427a6a2ba
=> DOCSP-37370 1.5.0 Release Notes

source/code-generation/query-converter.txt, source/code-generation/query-converter/convert-triggers.txt, source/includes/fact-query-converter-filter.rst, source/includes/fact-query-converter-generic.rst
Adding task page for Trigger conversions. Largely based on the stored procedure conversion task.
https://preview-mongodbianfmongodb.gatsbyjs.io/docs-relational-migrator/DOCSP-37055/code-generation/query-converter/convert-triggers/
https://jira.mongodb.org/browse/DOCSP-37055
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65e639ee11db7b0427720033
=> DOCSP-37055 Query Converter Triggers

source/installation.txt, source/installation/install-with-docker.txt
Adding docker installation task page to migrator installation drawer.
https://preview-mongodbianfmongodb.gatsbyjs.io/docs-relational-migrator/DOCSP-30182/installation/
https://preview-mongodbianfmongodb.gatsbyjs.io/docs-relational-migrator/DOCSP-30182/installation/install-with-docker/
https://jira.mongodb.org/browse/DOCSP-30182
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6605d50569c71c33fbdc0454
=> DOCSP-30182 Add Docker Install Page

source/includes/fact-kafka-supported-task.rst, source/jobs/pause-resume-kafka-jobs.txt
Adding links to Kafka configure pages for previous `ToDo` comments.
https://preview-mongodbianfmongodb.gatsbyjs.io/docs-relational-migrator/DOCSP-37918/jobs/pause-resume-kafka-jobs/#before-you-begin
https://preview-mongodbianfmongodb.gatsbyjs.io/docs-relational-migrator/DOCSP-37918/jobs/creating-jobs/#create-a-sync-job
https://jira.mongodb.org/browse/DOCSP-37918
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=661439813a5920a29146ddb0
=> DOCSP-37918 Add Kafka Install Links

source/includes/fact-data-prep-oracle-step1.rst, source/jobs/prerequisites/oracle.txt
1. Updated all `V_$` to `V$` in all view names.
2. Change `GRANT SELECT <table> TO <user>;` to `GRANT SELECT ANY TABLE TO <user>;`
3. Change `GRANT FLASHBACK ON <table> TO <user>;` to `GRANT FLASHBACK ANY TABLE TO <user>;`
4. Change `GRANT LOCK <table> TO <user>;` to `GRANT LOCK ANY TABLE TO <user>;`
https://preview-mongodbianfmongodb.gatsbyjs.io/docs-relational-migrator/DOCSP-38395/jobs/prerequisites/oracle/
https://jira.mongodb.org/browse/DOCSP-38395
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66142dd83a5920a291440886
=> DOCSP-38395 Oracle Prereq Fixes

source/getting-started/supported-databases.txt
Adding a footnote to the supported database page for Timescale db.
https://preview-mongodbianfmongodb.gatsbyjs.io/docs-relational-migrator/DOCSP-38451/getting-started/supported-databases/#footnote-1
https://jira.mongodb.org/browse/DOCSP-38451
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6616d0963a5920a291e9cf72
=> DOCSP-38451 Add Timescale DB Footnote to Supported Databases

source/release-notes.txt
1.6.0 release notes
https://preview-mongodbltranmdb2.gatsbyjs.io/docs-relational-migrator/DOCSP-38811/release-notes/
https://jira.mongodb.org/browse/DOCSP-38811
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=662272b1132d178bc1c6b4fa
=> DOCSP-38811 migrator 1.6.0 release notes

source/installation/install-on-an-unattended-server/rhel-centos-server-installation/install-rhel-server.txt
Correct `.deb` to `.rpm` in RHEL server install
https://preview-mongodbjocelynmendez1.gatsbyjs.io/docs-relational-migrator/DOCSP-38918/installation/install-on-an-unattended-server/rhel-centos-server-installation/install-rhel-server/#steps
https://jira.mongodb.org/browse/DOCSP-38918?filter=-1
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66292735b67dbf804adb52d7
=> DOCSP-38918 Correct `.deb` to `.rpm` in RHEL server install

source/installation/install-on-a-local-machine/install-mac.txt, source/installation/install-on-a-local-machine/install-on-a-local-machine.txt, source/installation/install-on-a-local-machine/install-rhel.txt, source/installation/install-on-a-local-machine/install-ubuntu.txt, source/installation/install-on-a-local-machine/install-windows.txt, source/installation/install-on-an-unattended-server/debian-server-installation/install-debian-server.txt, source/installation/install-on-an-unattended-server/rhel-centos-server-installation/install-rhel-server.txt
Update MySQL JDBC 8.0 driver to 8.3
[Local Installation](https://preview-mongodbjocelynmendez1.gatsbyjs.io/docs-relational-migrator/DOCSP-38917/installation/install-on-a-local-machine/install-on-a-local-machine/#behavior)
[Install on Windows](https://preview-mongodbjocelynmendez1.gatsbyjs.io/docs-relational-migrator/DOCSP-38917/installation/install-on-a-local-machine/install-windows/#steps)
[Install on Mac](https://preview-mongodbjocelynmendez1.gatsbyjs.io/docs-relational-migrator/DOCSP-38917/installation/install-on-a-local-machine/install-mac/#steps)
[Install on Ubuntu](https://preview-mongodbjocelynmendez1.gatsbyjs.io/docs-relational-migrator/DOCSP-38917/installation/install-on-a-local-machine/install-ubuntu/#steps)
[Install on …
=> DOCSP-38917 Update MySQL JDBC 8.0 driver to 8.3

source/code-generation/query-converter/convert-queries.txt, source/code-generation/query-converter/convert-stored-procedures.txt, source/code-generation/query-converter/convert-triggers.txt, source/code-generation/query-converter/convert-views.txt, source/includes/fact-query-converter-failure-errors.rst
Add note where the query converter errors are located.
https://preview-mongodbianfmongodb.gatsbyjs.io/docs-relational-migrator/DOCSP-32494/code-generation/query-converter/convert-views/
https://preview-mongodbianfmongodb.gatsbyjs.io/docs-relational-migrator/DOCSP-32494/code-generation/query-converter/convert-triggers/
https://preview-mongodbianfmongodb.gatsbyjs.io/docs-relational-migrator/DOCSP-32494/code-generation/query-converter/convert-stored-procedures/
https://preview-mongodbianfmongodb.gatsbyjs.io/docs-relational-migrator/DOCSP-32494/code-generation/query-converter/convert-queries/
https://jira.mongodb.org/browse/DOCSP-32494
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6629562fb67dbf804aeefaef …
=> DOCSP-32494 Add Query Converter Error Include

source/code-generation/query-converter/convert-queries.txt
Add an optional step to provide feedback on converted queries to improve future conversion.
https://preview-mongodbjocelynmendez1.gatsbyjs.io/docs-relational-migrator/DOCSP-33101/code-generation/query-converter/convert-queries/#-optional--provide-feedback-on-the-converted-query
https://jira.mongodb.org/browse/DOCSP-33101
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6633c2ebb67dbf804a5b1caf
=> DOCSP-33101 Converted Query feedback

source/mapping-rules/mapping-rule-options/mapping-rule-options.txt, source/mapping-rules/mapping-rule-options/rename-collection.txt, source/mapping-rules/new-rules-to-mongodb.txt
Rename a collection in mappings pane when creating mappings rules.
https://preview-mongodbjocelynmendez1.gatsbyjs.io/docs-relational-migrator/DOCSP-29175/mapping-rules/mapping-rule-options/rename-collection/
https://jira.mongodb.org/browse/DOCSP-29175
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6633a515b67dbf804a4e8295
=> DOCSP-29175 Add how to rename collection 

source/mapping-rules/new-rules-suggested-mappings.txt
Ignore suggested mappings.
https://preview-mongodbjocelynmendez1.gatsbyjs.io/docs-relational-migrator/DOCSP-30154/mapping-rules/new-rules-suggested-mappings/#steps
https://jira.mongodb.org/browse/DOCSP-30154
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6633b58fb67dbf804a56995d
=> DOCSP-30154 Ignore suggested mappings

source/projects/create-project-live-connection.txt
Update database name requirement for SQL & Sybase
https://preview-mongodbjocelynmendez1.gatsbyjs.io/docs-relational-migrator/DOCSP-33077/projects/create-project-live-connection/#steps
https://jira.mongodb.org/browse/DOCSP-33077
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=663e6335b67dbf804ac9cf95
=> DOCSP-33077 Update database name requirement for SQL & Sybase

source/release-notes.txt
- Release notes for Migrator `1.7` bug fixes + features.
- Added a link to the time series migration content in `1.6` release notes.
https://preview-mongodbianfmongodb.gatsbyjs.io/docs-relational-migrator/DOCSP-39386/release-notes/#1.7.0-changelog
https://jira.mongodb.org/browse/DOCSP-39386
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66474850cf5bec1c29591d45
=> DOCSP-39386 Relational Migrator 1.7 Release Notes

build.sh, netlify.toml
This adds the scripts and configuration needed to build sites with Netlify out of the box.
=> Configure site for Netlify roll out

snooty.toml, source/code-generation/query-converter-test-bench.txt, source/code-generation/query-converter.txt, source/code-generation/query-converter/query-converter-test-bench/compare-converted-queries.txt
https://preview-mongodbianfmongodb.gatsbyjs.io/docs-relational-migrator/DOCSP-40890/code-generation/query-converter-test-bench/
=> DOCSP-40890 Stage Query Converter Test Bench TOC

source/installation/install-on-an-unattended-server/debian-server-installation/install-debian-server.txt, source/installation/install-on-an-unattended-server/rhel-centos-server-installation/install-rhel-server.txt, source/projects/project-settings.txt
Remove unnecessary installation step 3. Currently, decided to remove it because step 5 appears to make it unnecessary but can roll into step 4 pending engineering feedback. 
- [Debian instructions](https://preview-mongodbjocelynmendez1.gatsbyjs.io/docs-relational-migrator/DOCSP-40418/installation/install-on-an-unattended-server/debian-server-installation/install-debian-server/)
- [RHEL instructions](https://preview-mongodbjocelynmendez1.gatsbyjs.io/docs-relational-migrator/DOCSP-40418/installation/install-on-an-unattended-server/rhel-centos-server-installation/install-rhel-server/)
https://jira.mongodb.org/browse/DOCSP-40418?filter=-1
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6697e76826eba79552be04ad …
=> DOCSP-40418 Remove unnecessary steps

source/code-generation/query-converter-test-queries.txt, source/code-generation/query-converter/test-converted-queries/compare-converted-queries.txt, source/code-generation/query-converter/test-converted-queries/install-query-runner.txt
- Task page.
https://preview-mongodbianfmongodb.gatsbyjs.io/docs-relational-migrator/DOCSP-40960/code-generation/query-converter/test-converted-queries/compare-converted-queries/
https://jira.mongodb.org/browse/DOCSP-40960
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66b632bd8383957117ade324
=> DOCSP-40960-compare-queries-task

source/code-generation.txt, source/code-generation/generate-app-code.txt, source/code-generation/query-converter-test-queries.txt, source/code-generation/query-converter.txt, source/connection-strings/connection-strings.txt, source/diagrams/diagrams.txt, source/diagrams/manage-diagrams.txt, source/diagrams/navigate-diagrams/navigate-diagrams.txt, source/diagrams/navigate-diagrams/working-with-entities/working-with-entities.txt, source/getting-started.txt, source/index.txt, source/installation.txt, source/installation/install-on-a-local-machine/install-on-a-local-machine.txt, source/installation/install-on-an-unattended-server/debian-server-installation/debian-server-installation.txt, source/installation/install-on-an-unattended-server/install-on-an-unattended-server.txt, source/installation/install-on-an-unattended-server/rhel-centos-server-installation/rhel-centos-server-installation.txt, source/installation/install-on-an-unattended-server/windows-server-installation/windows-server-installation.txt, source/installation/kafka-deployments/migrator-with-kafka.txt, source/jobs/data-verification/data-verification.txt, source/jobs/prerequisites.txt, source/jobs/sync-jobs.txt, source/mapping-rules/fields/calculated-fields/calculated-fields.txt, source/mapping-rules/fields/field-customizations.txt, source/mapping-rules/mapping-rule-options/mapping-rule-options.txt, source/mapping-rules/mapping-rules.txt, source/mapping-rules/synthetic-foreign-key/synthetic-foreign-keys.txt, source/projects/projects.txt, source/table-filters/table-filters.txt
Updated ToC based on the [new ToC style guidelines](https://www.mongodb.com/docs/meta/style-guide/style/toc-labels/)
https://deploy-preview-164--docs-relational-migrator.netlify.app
all ToC labels can be viewed through the menu drop downs
https://jira.mongodb.org/browse/DOCSP-43306
https://app.netlify.com/sites/docs-relational-migrator/deploys/66e0af9c2d167100071f5c97
=> DOCSP-43306-ToC-Refactor

source/installation/kafka-deployments/install-confluent-kafka.txt
Fixed two procedures within a procedure.
https://deploy-preview-167--docs-relational-migrator.netlify.app/installation/kafka-deployments/install-confluent-kafka/
https://jira.mongodb.org/browse/DOCSP-42970
https://app.netlify.com/sites/docs-relational-migrator/deploys/66ec6135422b8a0008762a1e
=> DOCSP-42970-relational-migrator-nested-components

source/code-generation/query-converter.txt, source/code-generation/query-converter/bulk-conversion.txt, source/includes/fact-query-converter-generic.rst, source/includes/fact-view-query-conversion-bulk-status.rst, source/includes/fact-view-query-conversion-history.rst
Provisioning the task page for Bulk Conversion and adding it to ToC structure.
[Code Generation > Query Converter > Bulk Conversion](https://deploy-preview-168--docs-relational-migrator.netlify.app/code-generation/query-converter/bulk-conversion/)
https://jira.mongodb.org/browse/DOCSP-43736
See [Netlify deploy log](https://github.com/mongodb/docs-relational-migrator/pull/168#issuecomment-2364209843) comment.
=> DOCSP-43736-Bulk-Conversions-Task-Page

source/release-notes.txt, source/rm-openapi-latest.json
Release notes for `v1.10`.
[Release Notes](https://deploy-preview-170--docs-relational-migrator.netlify.app/release-notes/)
https://jira.mongodb.org/browse/DOCSP-43809
=> DOCSP-43809: v1.10.0 Release Notes

snooty.toml, source/code-generation/query-converter.txt, source/code-generation/query-converter/bulk-conversion.txt, source/code-generation/query-converter/query-management.txt, source/code-generation/query-converter/query-management/download-queries.txt, source/code-generation/query-converter/query-management/filter-queries.txt, source/includes/fact-query-converter-generic.rst, source/includes/fact-view-query-conversion-bulk-status.rst, source/release-notes.txt
Merging Bulk Conversion feature branch into main.
https://jira.mongodb.org/browse/DOCSP-39042
=> Merging Bulk Conversion Feature Branch

source/release-notes.txt, source/rm-openapi-latest.json
Adding generated OpenAPI spec for `v1.10.0` release.
=> v1-10-OpenAPI-Update

source/jobs/sync-jobs.txt
Documenting non-impodency behavior for sync jobs.
https://deploy-preview-173--docs-relational-migrator.netlify.app/jobs/sync-jobs/#behavior
https://jira.mongodb.org/browse/DOCSP-43808
=> DOCSP-43808 document non idempotent inserts

source/jobs/sync-jobs.txt
Adds information about indexes created/not created during migration. 
https://deploy-preview-177--docs-relational-migrator.netlify.app/jobs/sync-jobs/#indexes
https://jira.mongodb.org/browse/DOCSP-33788
=> DOCSP-33788-migration-indexes

source/api-docs/rest-api-spec.txt, source/release-notes.txt, source/rm-openapi-latest.json
Adds 1.11 release notes and updates OpenAPI spec doc
- [OpenAPI spec](https://deploy-preview-182--docs-relational-migrator.netlify.app/api-docs/rest-api-spec/)
- generated with `npx openapi-format@latest build/openapi.json -o build/openapi.json --filterFile public-filter.yml` from app repo
- [Release notes](https://deploy-preview-182--docs-relational-migrator.netlify.app/release-notes/)
https://jira.mongodb.org/browse/DOCSP-45453
=> DOCSP-45453 1.11 release notes

source/getting-started/migration-scenarios.txt
Remove the inaccurate unsupported scenario.
[Currently Unsupported Migration Scenarios](https://deploy-preview-184--docs-relational-migrator.netlify.app/getting-started/migration-scenarios/#unsupported-migration-scenarios)
https://jira.mongodb.org/browse/DOCSP-45622
=> DOCSP-45622-remove-unsupported-scenario

source/code-generation/query-converter.txt, source/code-generation/query-converter/convert-oracle-packages.txt, source/code-generation/query-converter/convert-stored-procedures.txt, source/includes/fact-query-converter-filter.rst, source/includes/fact-query-converter-generic.rst, source/includes/query-conversion-examples/oracle-package-csharp.rst, source/includes/query-conversion-examples/oracle-package-java.rst, source/includes/query-conversion-examples/oracle-package-js.rst, source/includes/query-conversion-examples/oracle-package-original.rst
Adds page with instructions for converting oracle packages.
Adds new page to the ToC.
Updates convert stored procedures to note that MS SQL functions are converted with the same procedure.
Note for reviewer:
- I am working to get vetted code samples from an SME for Java and C#. These are intentionally blank for now.
- [Convert Oracle Packages](https://deploy-preview-186--docs-relational-migrator.netlify.app/code-generation/query-converter/convert-oracle-packages/) - new page
- [Convert Stored Procedures](https://deploy-preview-186--docs-relational-migrator.netlify.app/code-generation/query-converter/convert-stored-procedures/#convert-stored-procedures) - intro paragraph, new sentence referencing MS SQL Functions
https://jira.mongodb.org/browse/DOCSP-45372 …
=> DOCSP-45372 Adds convert oracle packages page

config/redirects
Updates redirects to make sure the syntax is consistent
mut-redirects config/redirects output:
Redirect 301 /docs/relational-migrator/projects/projects/ 
https://www.mongodb.com/docs/relational-migrator/projects/
Redirect 301 /docs/relational-migrator/table-filters/table-filters/ 
https://www.mongodb.com/docs/relational-migrator/table-filters/
Redirect 301 /docs/relational-migrator/installation/install-on-an-unattended-server/rhel-centos-server-installation/rhel-centos-server-installation/ 
https://www.mongodb.com/docs/relational-migrator/installation/install-on-an-unattended-server/rhel-centos-server-installation/
Redirect 301 /docs/relational-migrator/installation/install-on-an-unattended-server/windows-server-installation/windows-server-installation/ …
=> DOCSP-46723 making redirects consistent

config/redirects
Cleaning up some redirects that got lost in merge / ports:
- Added redirects from https://github.com/mongodb/docs-relational-migrator/pull/198
- Re-ordered redirects by DOCSP ticket number
- Edited descriptions + removed "start/end" lines for consistency
Added missing redirects for the following:
[Working With Entities](https://deploy-preview-202--docs-relational-migrator.netlify.app/diagrams/navigate-diagrams/working-with-entities) 
[Installation on a Local Machine](https://deploy-preview-202--docs-relational-migrator.netlify.app/installation/install-on-a-local-machine)
The added ones:
- Redirect 301 /docs/relational-migrator/diagrams/navigate-diagrams/working-with-entities/working-with-entities/ https://www.mongodb.com/docs/relational-migrator/diagrams/navigate-diagrams/working-with-enti …
=> DOCSP-46841 Added omitted redirects

source/installation/kafka-deployments/install-kafka-cluster.txt
Add note on "Install w/ Existing Kafka Cluster" page that the user should have pre-existing knowledge of Kafka. 
https://deploy-preview-203--docs-relational-migrator.netlify.app/installation/kafka-deployments/install-kafka-cluster/#install-with-an-existing-kafka-cluster
https://jira.mongodb.org/browse/DOCSP-46770
See the [taxonomy tagging instructions](https://wiki.corp.mongodb.com/display/DE/Taxonomy+tagging+instructions) and this [example PR](https://github.com/10gen/cloud-docs/pull/5042/files) 
=> DOCSP-46770-install-with-kafka-update

source/jobs/creating-jobs.txt
- Notes the new Atlas performance section in the Review Summary when creating a migration job
- Copy edits for brevity
[Create a Migration Job](https://deploy-preview-204--docs-relational-migrator.netlify.app/jobs/creating-jobs/#review-and-start-your-migration-job)
https://jira.mongodb.org/browse/DOCSP-42126
=> DOCSP-42126 Atlas performance guidance

source/release-notes.txt, source/rm-openapi-latest.json
1.12.0 Release notes
https://deploy-preview-205--docs-relational-migrator.netlify.app/release-notes/
https://deploy-preview-205--docs-relational-migrator.netlify.app/api-docs/rest-api-spec/
https://jira.mongodb.org/browse/DOCSP-46930
=> DOCSP-46930-1.12.0-release-notes

source/installation/install-on-an-unattended-server/debian-server-installation/install-debian-server.txt
Updates the debian linux install instructions to address frequent questions
https://deploy-preview-216--docs-relational-migrator.netlify.app/installation/install-on-an-unattended-server/debian-server-installation/install-debian-server/
https://jira.mongodb.org/browse/DOCSP-48175
=> DOCSP-48175 Updates debian server install instructions

source/installation/install-with-docker.txt
Adds note to the docker documentation clarifying that it is for local development only
- The build log contains many `Page not included in any toctree...` errors
- Pages are being left in place for now to facilitate: 
- creation of redirects before publishing feature branch 
https://deploy-preview-214--docs-relational-migrator.netlify.app/installation/install-with-docker/#install-with-docker
https://jira.mongodb.org/browse/DOCSP-47550
=> DOCSP-47550 Update the docker documentation

source/includes/fact-data-prep-oracle-step1.rst, source/jobs/prerequisites/oracle.txt
Ports #220 to docs-uplift branch
=> DOCSP-48310 Fixes typos in oracle db configuration script (#220)

source/api-developer-reference.txt, source/includes/fact-file-location-linux.rst, source/includes/fact-file-location-mac.rst, source/includes/fact-file-location-windows.rst, source/index.txt, source/installation/file-location.txt, source/installation/install-on-a-local-machine/install-mac.txt, source/installation/install-on-a-local-machine/install-rhel.txt, source/installation/install-on-a-local-machine/install-ubuntu.txt, source/installation/install-on-a-local-machine/install-windows.txt, source/installation/install-on-an-unattended-server/debian-server-installation.txt, source/installation/install-on-an-unattended-server/debian-server-installation/debian-system-service.txt, source/installation/install-on-an-unattended-server/debian-server-installation/install-debian-server.txt, source/installation/install-on-an-unattended-server/rhel-centos-server-installation.txt, source/installation/install-on-an-unattended-server/rhel-centos-server-installation/install-rhel-server.txt, source/installation/install-on-an-unattended-server/rhel-centos-server-installation/rhel-system-service.txt, source/installation/install-on-an-unattended-server/windows-server-installation.txt, source/installation/install-on-an-unattended-server/windows-server-installation/install-windows-server.txt, source/installation/install-on-an-unattended-server/windows-server-installation/windows-external-access.txt, source/installation/install-on-an-unattended-server/windows-server-installation/windows-system-service.txt
Updates the OS installation pages to make them self contained
Adds the following to the OS installation pages as applicable:
- File locations
- Run as a system service
- Enable external access
Local Install
- [Windows](https://deploy-preview-218--docs-relational-migrator.netlify.app/installation/install-on-a-local-machine/install-windows/)
- [MacOS](https://deploy-preview-218--docs-relational-migrator.netlify.app/installation/install-on-a-local-machine/install-ma …
=> DOCSP-47552 Updates the OS installation pages

source/database-connections/additional-options.txt, source/database-connections/database-connections.txt, source/database-connections/migrator-without-live-connection.txt
Adds details re: alternative connection options, connection "use cases", and creating a project with a live database connection.
https://deploy-preview-210--docs-relational-migrator.netlify.app/database-connections/database-connections/
https://jira.mongodb.org/browse/DOCSP-47554
=> DOCSP-47554 Update Connect to Databases landing page

source/installation/install-on-an-unattended-server.txt
Updates the Production Installation Guide landing page to detail use cases.
Specifically:
- Note that configuring monitoring and alerting is recommended for jobs > 1 week
- Recommend Kafka for critical producion jobs requiring high availability
https://deploy-preview-228--docs-relational-migrator.netlify.app/installation/install-on-an-unattended-server/#use-case
https://jira.mongodb.org/browse/DOCSP-47551 …
=> DOCSP-47551 Update the Production Installation Guide

source/installation/install-on-a-local-machine.txt
Updates the developer installation guide to include references to docker
https://deploy-preview-229--docs-relational-migrator.netlify.app/installation/install-on-a-local-machine/
https://jira.mongodb.org/browse/DOCSP-47549
=> DOCSP-47549 updates developer installation guide

source/jobs/sync-jobs.txt
Add compatibility section to data migration page.
https://deploy-preview-231--docs-relational-migrator.netlify.app/jobs/sync-jobs/#compatibility
https://jira.mongodb.org/browse/DOCSP-47782
=> DOCSP-47782: Update Data Migration page

source/installation/system-requirements.txt, source/jobs/sync-jobs.txt
Remove reference to Prerequisites page and remove it from TOC
https://deploy-preview-225--docs-relational-migrator.netlify.app/installation/system-requirements/#supported-databases
https://jira.mongodb.org/browse/DOCSP-47564
=> DOCSP-47564: Remove Prerequisites page

source/diagrams.txt
Adds description of diagrams.
https://deploy-preview-233--docs-relational-migrator.netlify.app/diagrams/
https://jira.mongodb.org/browse/DOCSP-47563
=> DOCSP-47563: Update Diagrams & Entities page

snooty.toml, source/mapping-rules/fields/calculated-fields/customized-id-fields.txt
Adds sentence about calculated fields.
https://deploy-preview-227--docs-relational-migrator.netlify.app/mapping-rules/fields/calculated-fields/customized-id-fields/
https://jira.mongodb.org/browse/DOCSP-47562
=> DOCSP-47562: Calculated Fields

source/jobs/sync-jobs.txt
Review the `Log In with Atlas` page to identify the correct location in the ToC
Notes:
- Added it to migration jobs before the `Create` step bc Log In with Atlas is used 2 places
- Enables selecting atlas instances from a dropdown when creating a migration job.
- Query converter needs Atlas log in to work
- Seemed more appropriate to include it before creating a migration job. Query converter docs already include a link to this doc where needed.
https://deploy-preview-238--docs-relational-migrator.netlify.app/getting-started/atlas-log-in/
https://jira.mongodb.org/browse/DOCSP-47566
=> DOCSP-47566 Review Log In with Atlas

source/mapping-rules/create-rules.txt, source/mapping-rules/new-rules-from-relational.txt, source/mapping-rules/new-rules-to-mongodb.txt
Condenses mapping rules into one page.
https://deploy-preview-239--docs-relational-migrator.netlify.app/mapping-rules/create-rules/
https://jira.mongodb.org/browse/DOCSP-47560
=> DOCSP-47560: mapping rules

source/getting-started.txt, source/index.txt
Updates "Introduction" ToC label to "Overview" and makes corresponding page title update
https://deploy-preview-240--docs-relational-migrator.netlify.app/getting-started/
https://jira.mongodb.org/browse/DOCSP-48656
=> DOCSP-48656 Updates Introduction ToC label and title

source/includes/fact-cloud-networking-considerations.rst, source/includes/fact-general-firewall-considerations.rst, source/includes/fact-hardware-considerations.rst, source/includes/fact-location-considerations.rst, source/includes/fact-telemetry.rst, source/installation.txt, source/installation/install-on-a-local-machine.txt, source/installation/install-on-an-unattended-server.txt
Updates the installation landing page to incorporate content currently found in `deployment-considerations.txt`
https://deploy-preview-217--docs-relational-migrator.netlify.app/installation/
https://jira.mongodb.org/browse/DOCSP-47548
=> DOCSP-47548 Updates the installation page to include deployment considerations

source/database-connections/oracle.txt, source/mapping-rules/schema-mapping.txt
Documents that materialized views are support for Oracle (and only Oracle)
https://deploy-preview-245--docs-relational-migrator.netlify.app/database-connections/oracle/#connect-to-oracle
https://deploy-preview-245--docs-relational-migrator.netlify.app/mapping-rules/schema-mapping/#mapping-rules
https://jira.mongodb.org/browse/DOCSP-48624
=> DOCSP-48624 documents oracle materialized view support in docs-uplift

source/release-notes.txt
High-priority bugfix release requested to address the following issues. Release 1.13.1 is planned for tomorrow 30 April AUST time, 29 April USA time.
[1.13.1 Changelog](https://deploy-preview-251--docs-relational-migrator.netlify.app/release-notes/#1.13.1-changelog)
https://jira.mongodb.org/browse/DOCSP-49615
=> DOCSP-49615-Relational-Migrator-1.13.1-release-notes

source/release-notes.txt
Fast-follow for small formatting error.
https://jira.mongodb.org/browse/DOCSP-50268
=> DOCSP-50268-Release-notes-Relational-Migrator-1.13.2-fast-follow
