mongodb/docs-relational-migrator

source/diagrams/navigate-diagrams/apply-layout.txt, source/diagrams/navigate-diagrams/navigate-diagrams.txt, source/projects/create-project-live-connection.txt
Navigate Diagrams and Entities Drawer conversion from markdown to snooty.
Tabbed the images so they do not take up as much page real estate, also lightly reworded page content.
https://docs-mongodbcom-staging.corp.mongodb.com/docs-relational-migrator/docsworker-xlarge/DOCSP-30630/diagrams/navigate-diagrams/navigate-diagrams/
https://docs-mongodbcom-staging.corp.mongodb.com/docs-relational-migrator/docsworker-xlarge/DOCSP-30630/diagrams/navigate-diagrams/apply-layout/
https://jira.mongodb.org/browse/DOCSP-30630
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6489cb1d67a273b81627cd9a
=> DOCSP-30630 Navigate Diagrams and Entities Drawer

source/code-generation/code-generation.txt, source/connection-strings/mongodb-database-connection-strings.txt, source/connection-strings/relational-database-connection-strings.txt, source/jobs/creating-jobs.txt, source/jobs/monitoring-jobs.txt, source/jobs/stopping-jobs.txt, source/jobs/sync-jobs.txt, source/mapping-rules/calculated-fields/add-calculated-fields.txt
Sync Job drawer conversion from markdown to snooty.
https://docs-mongodbcom-staging.corp.mongodb.com/docs-relational-migrator/docsworker-xlarge/DOCSP-30628/jobs/sync-jobs/
https://docs-mongodbcom-staging.corp.mongodb.com/docs-relational-migrator/docsworker-xlarge/DOCSP-30628/jobs/creating-jobs/
https://docs-mongodbcom-staging.corp.mongodb.com/docs-relational-migrator/docsworker-xlarge/DOCSP-30628/jobs/monitoring-jobs/
https://docs-mongodbcom-staging.corp.mongodb.com/docs-relational-migrator/docsworker-xlarge/DOCSP-30628/jobs/stopping-jobs/
https://jira.mongodb.org/browse/DOCSP-30628
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64886cb367a273b816d5ff9b
=> DOCSP-30628 Migrate Sync Jobs Drawer

source/mapping-rules/calculated-fields/add-calculated-fields.txt, source/mapping-rules/calculated-fields/calculated-fields.txt, source/mapping-rules/calculated-fields/delete-calculated-fields.txt, source/mapping-rules/calculated-fields/edit-calculated-fields.txt, source/mapping-rules/calculated-fields/view-calculated-fields.txt, source/mapping-rules/new-rules-suggested-mappings.txt, source/mapping-rules/new-rules-to-mongodb.txt
Add new pages for Calculated Fields
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=648b354567a273b816815ecb
- [Calculated Fields](https://docs-mongodbcom-staging.corp.mongodb.com/docs-relational-migrator/docsworker-xlarge/DOCSP-30632/mapping-rules/calculated-fields/calculated-fields/)
- [Add Calculated Fields](https://docs-mongodbcom-staging.corp.mongodb.com/docs-relational-migrator/docsworker-xlarge/DOCSP-30632/mapping-rules/calculated-fields/add-calculated-fields/)
- Note, for this page I ended up reworking the examples section. Previously, all of the examples were in a [single table](http://docs-migrator.s3-website-us-east-1.amazonaws.com/main/Mapping-Rules/calculated-fields/add-calculated-fields/#examples), but the columns were too narrow to parse. I …
=> (DOCSP-30632): Migrate calculate fields 

source/installation/install-on-a-single-machine/install-rhel.txt
Correct first step of Install RHEL to say `.rpm` binary.
STAGING: https://docs-mongodbcom-staging.corp.mongodb.com/docs-relational-migrator/docsworker-xlarge/DOCSP-30906/installation/install-on-a-single-machine/install-rhel/
JIRA: https://jira.mongodb.org/browse/DOCSP-30906
BUILD: https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6494a4d5423952aeb9811536
=> DOCSP-30906 update to rpm in RHEL

source/installation/install-on-a-single-machine/install-on-a-single-machine.txt
Added xdb driver bullet for migrating tables that contain the `XML` type. 
STAGING: https://docs-mongodbcom-staging.corp.mongodb.com/docs-relational-migrator/docsworker-xlarge/DOCSP-31276/installation/install-on-a-single-machine/install-on-a-single-machine/#behavior 
JIRA: https://jira.mongodb.org/browse/DOCSP-31276
BUILD LOG: https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64b02a8a423952aeb9003c8a
=> DOCSP-31276 xdb driver

snooty.toml, source/installation.txt, source/installation/file-location.txt, source/installation/install-on-a-single-machine/install-mac.txt, source/installation/install-on-a-single-machine/install-on-a-single-machine.txt, source/installation/install-on-a-single-machine/install-rhel.txt, source/installation/install-on-a-single-machine/install-ubuntu.txt, source/installation/install-on-a-single-machine/install-windows.txt, source/installation/install-on-an-unattended-server/debian-server-installation/install-debian-server.txt, source/installation/install-on-an-unattended-server/install-on-an-unattended-server.txt, source/installation/install-on-an-unattended-server/rhel-centos-server-installation/install-rhel-server.txt, source/installation/install-on-an-unattended-server/windows-server-installation/install-windows-server.txt
Create reference page for file locations used in install pages.
STAGING: https://docs-mongodbcom-staging.corp.mongodb.com/docs-relational-migrator/docsworker-xlarge/DOCSP-27098/installation/file-location/#windows
JIRA: https://jira.mongodb.org/browse/DOCSP-27098?filter=-1
BUILD: https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64b181178d53f9c4af1cf6fa
=> DOCSP-27098 File location ref page

snooty.toml, source/projects/manage-relational-connection.txt
Small updates and improvements to the Manage the Relation Model page. Also updated `Connect DB` -> `Connect to database` since the UI has changed and adjusted terminology `migration jobs` -> `sync jobs` for consistency.
https://docs-mongodbcom-staging.corp.mongodb.com/docs-relational-migrator/docsworker-xlarge/DOCSP-27700/projects/manage-relational-connection/
https://jira.mongodb.org/browse/DOCSP-27700
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64d6476c67dbe91010dcc431
=> DOCSP-27700 Manage the Relation Model Refactor

source/connection-strings/relational-database-connection-strings.txt
Fixed two links that were 404ing on the MySQL Connection string section.
https://preview-mongodbianfmongodb.gatsbyjs.io/docs-relational-migrator/DOCSP-33925/connection-strings/relational-database-connection-strings/#mysql
https://jira.mongodb.org/browse/DOCSP-33925
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=653facb7bd8a7a95793afebe
=> DOCSP-33925 Fix Relational Connection String 404s

source/mapping-rules/mapping-rules.txt
Adding links to data modeling content for the mapping rules page.
https://preview-mongodbianfmongodb.gatsbyjs.io/docs-relational-migrator/DOCSP-33437/mapping-rules/mapping-rules/#application-data-models
https://jira.mongodb.org/browse/DOCSP-33437
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=655bd0f25b686d6bd940dd38
=> DOCSP-33437 Add Data Modeling Links to Mapping Rules Page

source/connection-strings/mongodb-database-connection-strings.txt
Add details to the MongoDB connection string page that Relational Migrator supports all connection string options except appname when connecting to MongoDB.
https://preview-mongodbianfmongodb.gatsbyjs.io/docs-relational-migrator/DOCSP-34755/connection-strings/mongodb-database-connection-strings/
https://jira.mongodb.org/browse/DOCSP-34755
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6579fe387a5cb5fef5d1efe2
=> DOCSP-34755 Add Connection String Option Note

source/includes/fact-get-help-menu.rst, source/mapping-rules/schema-mapping.txt, source/projects/overview.txt
Add help menu context to UI page.
https://preview-mongodbianfmongodb.gatsbyjs.io/docs-relational-migrator/DOCSP-29066/projects/overview/
https://jira.mongodb.org/browse/DOCSP-29066
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65958590dcc0144a51b5fd49
=> DOCSP-29066 Add Help Menu Context to UI Page

source/includes/fact-my-sql-setup-user-permission-step.rst, source/includes/fact-short-sync-job-desc.rst, source/prerequisites.txt, source/prerequisites/my-sql.txt, source/prerequisites/oracle.txt, source/prerequisites/postgres.txt, source/prerequisites/sql-server.txt, source/prerequisites/sybase.txt
Includes data pre-req requirements for using Relational Migrator with MySQL. Also adding a generic page that states there are no pre-req requirements for Sybase ASE.
https://preview-mongodbianfmongodb.gatsbyjs.io/docs-relational-migrator/DOCSP-34352/prerequisites/my-sql/
https://preview-mongodbianfmongodb.gatsbyjs.io/docs-relational-migrator/DOCSP-34352/prerequisites/sybase/
https://jira.mongodb.org/browse/DOCSP-34352
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65c524916b2f17c95a3dfc35
=> DOCSP-34352 Add MySQL Data Prerequisite page

source/getting-started/supported-databases.txt
Update Oracle supported dbs to include 11g.
https://preview-mongodbjvincentmongodb.gatsbyjs.io/docs-relational-migrator/DOCSP-36552/getting-started/supported-databases/
https://jira.mongodb.org/browse/DOCSP-36552
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=660dd2253a5920a291d247a7
- [ x] Is this free of any warnings or errors in the RST?
- [x ] Is this free of spelling errors?
- [x ] Is this free of grammatical errors?
- [ x] Is this free of staging / rendering issues?
- [ x] Are all the links working?
=> DOCSP-36552 -- Update Oracle supported dbs to include 11g

source/code-generation/query-converter/convert-triggers.txt, source/release-notes.txt
Fixes some refs that were recently moved from the `cloud-docs` repo to the `app-services` repo.
https://preview-mongodbianfmongodb.gatsbyjs.io/docs-relational-migrator/DOCSP-38507/release-notes/#1.5.0-changelog
https://preview-mongodbianfmongodb.gatsbyjs.io/docs-relational-migrator/DOCSP-38507/code-generation/query-converter/convert-triggers/#convert-triggers
https://jira.mongodb.org/browse/DOCSP-38507
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6618021a3a5920a2913c498d
=> DOCSP-38507 Fix Atlas Trigger Refs

source/connection-strings/relational-database-connection-strings.txt, source/jobs/creating-jobs.txt, source/jobs/prerequisites.txt, source/jobs/prerequisites/sybase.txt, source/projects/create-project-live-connection.txt, source/projects/create-project-loading-schema-files.txt
Add Sybase mentions to the connection string page and other supplementary pages where the other RDMS's are mentioned. 
https://preview-mongodbianfmongodb.gatsbyjs.io/docs-relational-migrator/DOCSP-35064/connection-strings/relational-database-connection-strings/#sybase
https://preview-mongodbianfmongodb.gatsbyjs.io/docs-relational-migrator/DOCSP-35064/jobs/creating-jobs/
https://jira.mongodb.org/browse/DOCSP-35064
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66280179b67dbf804a902a0f
=> DOCSP-35064 Add Sybase Mentions to Corpus

source/jobs/creating-jobs.txt
Add the select a cluster option when creating a sync job
https://preview-mongodbjocelynmendez1.gatsbyjs.io/docs-relational-migrator/DOCSP-34858/jobs/creating-jobs/#steps
https://jira.mongodb.org/browse/DOCSP-34858?filter=-1
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=662a7c36b67dbf804a344f63
=> DOCSP-34858 Select a cluster option for new sync job

source/jobs/sync-jobs.txt
Changing the private preview note to a pointer to the Kafka docs instead, since Kafka is no longer in private preview.
https://preview-mongodbianfmongodb.gatsbyjs.io/docs-relational-migrator/DOCSP-39394/jobs/sync-jobs/
https://jira.mongodb.org/browse/DOCSP-39394
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=663b6a02b67dbf804a07e0da
=> DOCSP-39394 Remove Kafka Private Preview Note

source/includes/fact-restart-migrator-oracle-mysql-drivers.rst, source/installation/install-on-a-local-machine/install-mac.txt, source/installation/install-on-a-local-machine/install-rhel.txt, source/installation/install-on-a-local-machine/install-ubuntu.txt, source/installation/install-on-a-local-machine/install-windows.txt
- Adding a restart command to the windows install instructions.
- Added a note to the all install instructions that if you started the application before moving the odbc drivers into the driver folder you must restart.
https://preview-mongodbianfmongodb.gatsbyjs.io/docs-relational-migrator/DOCSP-39174/installation/install-on-a-local-machine/install-windows/
https://preview-mongodbianfmongodb.gatsbyjs.io/docs-relational-migrator/DOCSP-39174/installation/install-on-a-local-machine/install-ubuntu/
https://preview-mongodbianfmongodb.gatsbyjs.io/docs-relational-migrator/DOCSP-39174/installation/install-on-a-local-machine/install-rhel/
https://preview-mongodbianfmongodb.gatsbyjs.io/docs-relational-migrator/DOCSP-39174/installation/install-on-a-local-machine/install-mac/ …
=> DOCSP-39174 Add Restart Task Substep to Windows Instructions

source/includes/fact-cdc-recoverable.rst, source/includes/fact-resume-cdc-jobs.rst, source/jobs/creating-jobs.txt, source/jobs/recover-jobs.txt, source/jobs/sync-jobs.txt
- Adds `recover a sync job` page that outlines how to recover a failed sync job.
- Add small note to the create sync job page att section.
https://preview-mongodbianfmongodb.gatsbyjs.io/docs-relational-migrator/DOCSP-39099/jobs/sync-jobs/#recoverability
https://preview-mongodbianfmongodb.gatsbyjs.io/docs-relational-migrator/DOCSP-39099/jobs/recover-jobs/
https://preview-mongodbianfmongodb.gatsbyjs.io/docs-relational-migrator/DOCSP-39099/jobs/creating-jobs/
https://jira.mongodb.org/browse/DOCSP-39099
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66a0694826eba79552a04f64
=> DOCSP-39099 CDC Recoverability Content

source/installation/kafka-deployments/migrator-with-kafka.txt
Standardize spelling for "plugin". I only found one instance of "plug-in" in the docs that needed to be updated.
[Integrating Relational Migrator with Kafka](https://preview-mongodbjeffallenmongo.gatsbyjs.io/docs-relational-migrator/DOCSP-42470/installation/kafka-deployments/migrator-with-kafka/#integrating-relational-migrator-with-kafka)
https://jira.mongodb.org/browse/DOCSP-42470
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66bfaf018e811ae6728621ad
=> DOCSP-42470-plugin-spelling-change

source/installation/kafka-deployments/advanced-settings.txt
- Fixing naming error `migrator.connector.source.common` should be `migrator.connector.sink.common`.
https://preview-mongodbianfmongodb.gatsbyjs.io/docs-relational-migrator/DOCSP-42513/installation/kafka-deployments/advanced-settings/#sink-connector-properties
https://jira.mongodb.org/browse/DOCSP-42513
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66bbba398383957117cf6fff
=> DOCSP-42513-correct-source-common-name

snooty.toml, source/installation/kafka-deployments/install-kafka-cluster.txt
Updating Debezium links on Kafka Cluster Installation to version `2.7.0` final.
[Install with an Existing Kafka Cluster (Step 1)](https://deploy-preview-166--docs-relational-migrator.netlify.app/installation/kafka-deployments/install-kafka-cluster/#install-debezium-source-connect-plugin)
https://jira.mongodb.org/browse/DOCSP-43140
https://app.netlify.com/sites/docs-relational-migrator/deploys/66e336c25506d40007be00af
=> DOCSP-43140-Update-Debezium-Source-Version-to-2.7.0

source/connection-strings/connection-strings.txt
Replacing the ToC entry for `Connection Strings` > `Relational Database`. (Was `Connection Strings` > `Relational Migrator`).
[Connection Strings](https://deploy-preview-174--docs-relational-migrator.netlify.app/connection-strings/connection-strings/) (See ToC entry underneath `Connection Strings`)
https://jira.mongodb.org/browse/DOCSP-44455
=> DOCSP-44455-incorrect-heading-text

source/getting-started/supported-databases.txt
- Added DB2 (Public Preview) to supported databases: Support for Self-hosted and AWS RDS.
- Updated Sybase entry to mention its in Public Preview.
- Linked each database table entry to its Database prerequisite page.
- Moved Timescale into a row under Postgres.
[Supported Databases](https://deploy-preview-175--docs-relational-migrator.netlify.app/getting-started/supported-databases/)
https://jira.mongodb.org/browse/DOCSP-43831
=> DOCSP-43831-DB2-and-Sybase-database-support

source/projects/configure-settings.txt
Code block in Configuring Project Settings page in Relational Migrator docs reads:  `_id``field is ``_id: { personId: 1 }`; it should read `_id` field is `_id: { personId: 1 }`
https://deploy-preview-179--docs-relational-migrator.netlify.app/projects/configure-settings/#configurable-project-settings
https://jira.mongodb.org/browse/DOCSP-44814
=> DOCSP-44814-project-settings-malformed-code-block

source/release-notes.txt
Add a one liner with link to https://www.mongodb.com/docs/relational-migrator/release-notes/ showing where to download this release. Users who visit the release notes should be able to easily down
[DOCSP-45763](https://jira.mongodb.org/browse/DOCSP-45763)
=> (DOCSP-45763) [MIG] Add downloads page link to release notes

source/includes/fact-data-prep-oracle-step1.rst, source/includes/fact-short-sync-job-desc.rst, source/jobs/prerequisites/oracle.txt
- Explicitly calls out Oracle XE as unsupported for continuous migration
- Clarifies differences between multi-tenant and single tenant config
- Clarifies that logging setup is for archive + supplemental logging
[Configure Migration Prerequisites for Oracle](https://deploy-preview-188--docs-relational-migrator.netlify.app/jobs/prerequisites/oracle/#configure-migration-prerequisites-for-oracle)
https://jira.mongodb.org/browse/DOCSP-45339
=> DOCSP-45339 Update Oracle migration prerequisites

source/jobs/sync-jobs.txt, source/table-filters/table-filters.txt
Mention that snapshot jobs use table filters if present, but CDC jobs always ignore snapshot table filters and will update all database objects. From discussion at https://github.com/mongodb/docs-relational-migrator/pull/177
- [Migration Jobs](https://deploy-preview-187--docs-relational-migrator.netlify.app/jobs/sync-jobs/)
- [Table Filters](https://deploy-preview-187--docs-relational-migrator.netlify.app/table-filters/table-filters/) 
=> (DOCSP-45462) [MIG] Mention that CDC jobs ignore table filters

source/connection-strings/mongodb-database-connection-strings.txt, source/database-connections/save-mongodb-connection.txt, source/includes/steps-atlas-cluster.rst, source/includes/steps-create-mongodb-connection-short.rst
- Adds X.509 authentication info to the MongoDB Connection Strings topic
- Fixes some broken links to the core server docs
[MongoDB Connection Strings: Using X.509 Authentication](https://deploy-preview-206--docs-relational-migrator.netlify.app/connection-strings/mongodb-database-connection-strings/#using-x.509-authentication)
[Save a MongoDB Connection](https://deploy-preview-206--docs-relational-migrator.netlify.app/database-connections/save-mongodb-connection/#enter-the-mongodb-connection-string)
https://jira.mongodb.org/browse/DOCSP-46979
=> DOCSP-46979 X509 authentication

config/redirects
Adds redirects for pages moved in #104 
`mut-redirects config/redirects` output:
```
Redirect 301 /docs/relational-migrator/prerequisites/ https://www.mongodb.com/docs/relational-migrator/jobs/prerequisites/
Redirect 301 /docs/relational-migrator/prerequisites/my-sql/ https://www.mongodb.com/docs/relational-migrator/jobs/prerequisites/my-sql/
Redirect 301 /docs/relational-migrator/prerequisites/oracle/ https://www.mongodb.com/docs/relational-migrator/jobs/prerequisites/oracle/
Redirect 301 /docs/relational-migrator/prerequisites/postgres/ https://www.mongodb.com/docs/relational-migrator/jobs/prerequisites/postgres/
Redirect 301 /docs/relational-migrator/prerequisites/sql-server/ https://www.mongodb.com/docs/relational-migrator/jobs/prerequisites/sql-server/
Redirect 301 …
```
=> DOCSP-47252 adds redirects for moved prereq pages

source/code-generation/query-converter/convert-stored-procedures.txt
Remove deprecated link to app services on this page: https://www.mongodb.com/docs/relational-migrator/code-generation/query-converter/convert-stored-procedures/
https://deploy-preview-213--docs-relational-migrator.netlify.app/code-generation/query-converter/convert-stored-procedures/#before-you-begin
https://jira.mongodb.org/browse/DOCSP-47270
=> DOCSP-47270-remove-deprecated-appx-link

source/includes/fact-data-prep-oracle-step1.rst, source/jobs/prerequisites/oracle.txt
Updates the Oracle db configuration script to fix typos.
All `V$...` instances should be `V_$...` in step 1 parts C and D
https://deploy-preview-220--docs-relational-migrator.netlify.app/jobs/prerequisites/oracle/#set-up-user-permissions-1
https://jira.mongodb.org/browse/DOCSP-48310
=> DOCSP-48310 Fixes typos in oracle db configuration script

source/release-notes.txt
- Adds release notes for RM 1.13, scheduled for release 3/24. Merge and publish on 3/21.
- Fixed a couple of old typos.
[1.13.0 Changelog](https://deploy-preview-234--docs-relational-migrator.netlify.app/release-notes/#1.13.0-changelog)
https://jira.mongodb.org/browse/DOCSP-48536
The ref to the main Pre-Migration Analysis page links to a topic that will be merged in https://github.com/mongodb/docs-relational-migrator/pull/224
=> DOCSP-48536 Relational Migrator 1.13 release notes

snooty.toml, source/database-connections/migrator-without-live-connection.txt, source/projects/create-project-loading-schema-files.txt, source/projects/create-project-sample-schema.txt
Adds a landing page to describe using Rel. Mig. with a sample schema or by loading a DDL file
New landing page: https://deploy-preview-232--docs-relational-migrator.netlify.app/database-connections/migrator-without-live-connection/
New titles for the following pages:
- https://deploy-preview-232--docs-relational-migrator.netlify.app/projects/create-project-loading-schema-files/
- https://deploy-preview-232--docs-relational-migrator.netlify.app/projects/create-project-sample-schema/
https://jira.mongodb.org/browse/DOCSP-47556
=> DOCSP-47556 adds a page for using RM without a live connection

source/rm-openapi-latest.json
Adding Pre-Migration Analysis endpoints to the Relational Migrator API documentation.
This content is generated from [mongodb-ets/migrator](https://github.com/mongodb-ets/migrator). I'll have the team edit the source and generate new output with corrections after initial copy review.
https://deploy-preview-237--docs-relational-migrator.netlify.app/api-docs/rest-api-spec/
https://jira.mongodb.org/browse/DOCSP-48539
=> DOCSP-48539-PreMigration-Analysis-API-endpoints

source/database-connections/manage-database-connections.txt
Adds four places in UI to create a database connection.
https://deploy-preview-230--docs-relational-migrator.netlify.app/database-connections/manage-database-connections/#create-a-connection
https://jira.mongodb.org/browse/DOCSP-47796
=> DOCSP-47796: Database connections

source/database-connections/database-connections.txt, source/database-connections/manage-database-connections.txt, source/getting-started.txt, source/installation/application-settings.txt, source/projects.txt, source/projects/deleting-projects.txt, source/projects/export-project.txt, source/projects/import-project.txt, source/projects/manage-projects.txt, source/projects/project-settings.txt, source/projects/renaming-projects.txt
Refactors the projects section content.
Specifically:
- Updates "Manage Projects" page to parallel [Manage Connections](https://www.mongodb.com/docs/relational-migrator/database-connections/manage-database-connections/) format
- Updates titles and ToC labels
- Updates content on landing page to reflect these changes
- Moves Application-wide settings to the new "Application Settings" page
- [Projects Landing …
=> DOCSP-47557 Refactors projects section

source/includes/project-initial-mappings.rst, source/projects/create-project-live-connection.txt, source/projects/create-project-loading-schema-files.txt, source/projects/create-project-sample-schema.txt
Fixes issue where final steps of create project w/live DB were not rendered
Bug Fix:
- https://deploy-preview-242--docs-relational-migrator.netlify.app/projects/create-project-live-connection/#from-the-select-tables-screen--indicate-the-tables-you-want-to-migrate-and-click-next.
- Steps 3 -> end now show up
- Step 5 now renders the include properly
No visible changes:
- These pages used the `include` file that was modified and were updated to accommodate the change.
- https://deploy-preview-242--docs-relational-migrator.netlify.app/projects/create-project-loading-schema-files/#steps
- Step 7 
- https://deploy-preview-242--docs-relational-migrator.netlify.app/projects/create-project-sample-schema/#steps
- Step 6
https://jira.mongodb.org/browse/DOCSP-48658 …
=> DOCSP-48658 fixes rendering issue in create project w live DB

source/installation/kafka-deployments/install-docker.txt
Incorrect environmental variable. Instead of `MIGRATOR_DATA_PATH` it should be `MIGRATOR_PATH_DATA`.
[Configure Environmental Variables](https://deploy-preview-244--docs-relational-migrator.netlify.app/installation/kafka-deployments/install-docker/#configure-environment-variables)
https://jira.mongodb.org/browse/DOCSP-48729
=> DOCSP-48729-Update-Kafka-via-Docker-docs

config/redirects
Fixes bad redirects
Originally I redirected to `/database-connections/database-connections`.
This page was moved to `/database-connections` while the uplift project was in progress
N/A
https://jira.mongodb.org/browse/DOCSP-49304
=> DOCSP-49304 fixes bad redirects

source/includes/fact-data-prep-oracle-step1.rst, source/jobs/prerequisites/oracle.txt
Addressing backlog of updates for the migration requisites page for Oracle. A new tab contains the RDS specific instructions, with edits for all relevant feedback interlaced throughout the ticket.  Both Snapshot Jobs and Continuous Jobs had minor edits per feedback.
[Configure Migration Prerequisites for Oracle - Steps](https://deploy-preview-247--docs-relational-migrator.netlify.app/jobs/prerequisites/oracle/#steps):
- Snapshot Jobs
- Continuous Jobs
- Continuous Jobs (Amazon RDS)
https://jira.mongodb.org/browse/DOCSP-48670
=> DOCSP-48670-update-oracle-prereqs

.github/workflows/generate-bump-pages.yml, source/rm-openapi-latest.json
This PR introduces a GitHub integration for Bump.sh, the new OpenAPI spec renderer that we'll be using in place of our fork of Redoc. The goal of this is to have a simple integration that we can use to start publishing the Relational Migrator OpenAPI spec to Bump.
The workflow allows users to use Bump to create a preview when changes to the OpenAPI spec is found. When the change is merged to the `master` branch, it'll allow Bump to automatically publish the latest OpenAPI spec to prod.
Bump prints out a link to previews in the GH action ([example](https://github.com/mongodb/docs-relational-migrator/actions/runs/15122415555/job/42507608499#step:3:12)).
This should be similar to the workflow introduced for the Atlas Admin API ([see …
=> DOP-5496: Create GH action to deploy Bump pages
